pip install appdirs --upgrade
pip install astroid --upgrade
pip install attrs --upgrade
pip install beautifulsoup4 --upgrade
pip install black --upgrade
pip install blinker --upgrade
pip install certifi --upgrade
pip install chardet --upgrade
pip install Click --upgrade
pip install coinbase --upgrade
pip install colorama --upgrade
pip install crayons --upgrade
pip install decorator --upgrade
pip install docutils --upgrade
pip install emoji --upgrade
pip install entrypoints --upgrade
pip install feedgenerator --upgrade
pip install flake8 --upgrade
pip install future --upgrade
pip install gazpacho --upgrade
pip install gmusicapi --upgrade
pip install gpsoauth --upgrade
pip install httplib2 --upgrade
pip install idna --upgrade
pip install imutils --upgrade
pip install isort --upgrade
pip install Jinja2 --upgrade
pip install lazy-object-proxy --upgrade
pip install lxml --upgrade
pip install Markdown --upgrade
pip install MarkupSafe --upgrade
pip install mccabe --upgrade
pip install MechanicalSoup --upgrade
pip install mock --upgrade
pip install mutagen --upgrade
pip install numpy --upgrade
pip install oauth2client --upgrade
pip install opencv-python --upgrade
pip install pandas --upgrade
pip install pathspec --upgrade
pip install pelican --upgrade
pip install Pillow --upgrade
pip install proboscis --upgrade
pip install protobuf --upgrade
pip install pyasn1 --upgrade
pip install pyasn1-modules --upgrade
pip install pycodestyle --upgrade
pip install pycryptodome --upgrade
pip install pycryptodomex --upgrade
pip install pyflakes --upgrade
pip install Pygments --upgrade
pip install pylint --upgrade
pip install pytesseract --upgrade
pip install python-dateutil --upgrade
pip install pytz --upgrade
pip install regex --upgrade
pip install requests --upgrade
pip install rope --upgrade
pip install rsa --upgrade
pip install six --upgrade
pip install soupsieve --upgrade
pip install toml --upgrade
pip install typed-ast --upgrade
pip install Unidecode --upgrade
pip install urllib3 --upgrade
pip install validictory --upgrade
pip install wrapt --upgrade
pip install youtube-dl --upgrade
